### ISSUE TITLE
Ranked issues

### ISSUE THREAD

**Issue by CameronCT** [Keyma-sh/discord#12]
When using `k!user` it should display Unranked if Ranked Games Total are < 10.
This is intentionally not done in the API for reasons pertaining to React - therefore that's why it's not default'ly set the same way.

This issue also pertains to `k!roles` where it assigns a Gold rank despite Games Total being < 10.

**Comment by DefinitelyNotJah** [comment]
Will be included in the next update.

**Comment by CameronCT** [comment]
In the recent ranked update we made the rank name show Unranked if criteria of games aren't met. The k!rank role could probably just check the rank name and assign based on that (unless it's Unranked, then don't assign any role).
