### ISSUE TITLE
Roles should automatically remove all ranked/wpm roles prior to updating to new ones.

### ISSUE THREAD

**Issue by CameronCT** [Keyma-sh/discord#13]
`k!roles` has no where (at least from my knowledge) where it wipes previous roles before assigning current roles.

**Comment by DefinitelyNotJah** [comment]
That's true.
The fix/solution will be included in the next update but it's going to be a bit heavy because I'll have to loop through almost 10 roles, check every single one of them if the user has them and remove if he does.

If you have a more efficient solution, please let me know.
